### ISSUE TITLE
DAOD audit logging issues

### ISSUE THREAD

**Issue by nondeterminickstic** [IBM-i2/Analyze#79]
Hi, 
I've extended the opal-audit-csv-example to also log DAOD connector events and have this successfully running in several i2 Analyze deployments with no issues. 

In latest deployment however, i2 Analyze returns the following error at the top of the External Searches pane in ANBP during expand searches: 
"The i2 Analyze server failed to return the results of your search. Retry the operation or contact your system administrator"

I confirmed all returned search results were in fact correct, however the console.log file reports the following error: 

=============================================================
`2024-09-19 15:49:52,896 - [com.i2group.apollo.common.toolkit.internal.ConsoleLogger] - (opal-services-is-daod) - Errors occurred accessing system resources from DaodResourceDelegate. The likely cause is logged at FATAL.  (The full exception is logged at WARNING if enabled):
FATAL 2024-09-19 15:49:52,896 - com.i2group.opal.daod.internal.DaodResourceDelegate - Cannot invoke "java.util.List.iterator()" because "list" is null
2024-09-19 15:49:52,897 - [com.i2group.apollo.common.toolkit.internal.ConsoleLogger] - (opal-services-is-daod) - Cannot invoke "java.util.List.iterator()" because "list" is null
FATAL 2024-09-19 15:49:52,897 - com.i2group.opal.daod.internal.DaodResourceDelegate - 
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "list" is null
	at com.example.audit.CSVAuditLogger.buildListRepresentation(CSVAuditLogger.java:346) ~[opal-audit-csv-example.jar:?]
	at com.example.audit.CSVAuditLogger.mapListToString(CSVAuditLogger.java:277) ~[opal-audit-csv-example.jar:?]
	at com.example.audit.CSVAuditLogger.logDAODEvent(CSVAuditLogger.java:189) ~[opal-audit-csv-example.jar:?]
	at com.i2group.opal.daod.audit.internal.DAODAuditEventInterceptor.logDAODAuditEvent(DAODAuditEventInterceptor.java:93) ~[Daod.jar:4.4.3.0-7758]
	at com.i2group.opal.daod.audit.internal.DAODAuditEventInterceptor.auditDAODRequest(DAODAuditEventInterceptor.java:72) ~[Daod.jar:4.4.3.0-7758]
	at com.i2group.opal.daod.audit.internal.DAODAuditEventInterceptor.invoke(DAODAuditEventInterceptor.java:59) ~[Daod.jar:4.4.3.0-7758]
	at com.i2group.disco.audit.interceptors.internal.AuditInterceptorWrapper.invoke(AuditInterceptorWrapper.java:35) ~[AnalyzeCore.jar:4.4.3.0-7758]
	at com.i2group.disco.metric.internal.I2AnalyzeMetricsInterceptor.invoke(I2AnalyzeMetricsInterceptor.java:51) ~[AnalyzeCore.jar:4.4.3.0-7758]
	at com.i2group.disco.userloginsession.internal.UserLoginSessionInterceptor.invoke(UserLoginSessionInterceptor.java:41) ~[AnalyzeCore.jar:4.4.3.0-7758]
	at com.i2group.disco.common.interceptors.internal.BaseExpectedServerConfigInterceptor.invoke(BaseExpectedServerConfigInterceptor.java:98) ~[AnalyzeCore.jar:4.4.3.0-7758]
	at com.i2group.disco.common.http.cache.internal.CacheControlInterceptor.invoke(CacheControlInterceptor.java:21) ~[AnalyzeCore.jar:4.4.3.0-7758]
	at com.i2group.disco.common.interceptors.internal.DatabaseConnectionInterceptor.invoke(DatabaseConnectionInterceptor.java:34) ~[AnalyzeCore.jar:4.4.3.0-7758]
	at com.i2group.disco.common.interceptors.internal.ClientErrorExceptionInterceptor.invoke(ClientErrorExceptionInterceptor.java:25) ~[AnalyzeCore.jar:4.4.3.0-7758]
	at com.i2group.disco.common.interceptors.internal.ServerErrorExceptionInterceptor.invoke(ServerErrorExceptionInterceptor.java:38) ~[AnalyzeCore.jar:4.4.3.0-7758]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at com.i2group.disco.common.rest.internal.DynamicDelegateWrapper$DelegateWrapper$ProxyHandler.invoke(DynamicDelegateWrapper.java:183) [AnalyzeCore.jar:4.4.3.0-7758]
	at jdk.proxy7/jdk.proxy7.$Proxy337.acquireResultSet(Unknown Source) [?:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.performInvocation(LibertyJaxRsServerFactoryBean.java:649) [com.ibm.ws.jaxrs.2.1.server_1.0.81.jar:?]
	at [internal classes]
	at com.i2group.disco.common.filter.internal.SecureHeadersFilter.doFilter(SecureHeadersFilter.java:79) [AnalyzeCore.jar:4.4.3.0-7758]
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:203) [com.ibm.ws.webcontainer_1.1.81.jar:?]
	at [internal classes]
	at com.i2group.apollo.servlet.ResponseCodeFilter.doFilter(ResponseCodeFilter.java:75) [AnalyzeCore.jar:4.4.3.0-7758]
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:203) [com.ibm.ws.webcontainer_1.1.81.jar:?]
	at [internal classes]
	at com.i2group.disco.common.rest.internal.ScopeResetServletFilter.doFilter(ScopeResetServletFilter.java:25) [AnalyzeCore.jar:4.4.3.0-7758]
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:203) [com.ibm.ws.webcontainer_1.1.81.jar:?]
	at [internal classes]
	at com.i2group.disco.common.filter.internal.GZipFilter.doFilter(GZipFilter.java:48) [AnalyzeCore.jar:4.4.3.0-7758]
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:203) [com.ibm.ws.webcontainer_1.1.81.jar:?]
	at [internal classes]
	at com.i2group.disco.common.rest.internal.LoggingContextServletFilter.doFilter(LoggingContextServletFilter.java:113) [AnalyzeCore.jar:4.4.3.0-7758]
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:203) [com.ibm.ws.webcontainer_1.1.81.jar:?]
	at com.ibm.ws.webcontainer.fi
lter.WebAppFilterChain.doFilter(WebAppFilterChain.java:93) [com.ibm.ws.webcontainer_1.1.81.jar:?]
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:1068) [com.ibm.ws.webcontainer_1.1.81.jar:?]
	at [internal classes]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
`   
=============================================================

Disabling my auditing extension gets rid of the above errors (in ANBP and console.log) when performing expand searches, so it is definitely the root of the problem.

Clearly (from the console.log errors) my logging extension code is missing some 'null list' handling when processing the payload string returned by IDAODAuditEvent.getPayload(). Unfortunately I don't have a coding development environment in the customer's environment to enable thorough testing and I can't seem to replicate the issue in my local environment. 

Are you able to provide details on the actual structure of the payload string returned by IDAODAuditEvent.getPayload()? I think this will help me narrow down the issue. Unfortunately the i2 Analyze SDK documentation (https://i2group.github.io/analyze/docs/com/i2group/disco/audit/IDAODAuditEvent.html#getPayload()) appears to be missing this information.

Cheers!

**Comment by Afira-Zahari-i2** [comment]
Hello, the payload structure returned by `IDAODAuditEvent.getPayload()` is not public. In most cases, the whole payload returned as a string is sufficient for logging. Is there a reason you are processing the payload? Is there a particular field that you are trying to extract out of it (e.g., the form conditions of the expand)?

**Comment by nondeterminickstic** [comment]
Hi Afira,

I process the payload as most of our customers request a bit more control over what is being logged when their users perform searches via i2 Connect. Essentially there is a lot of information available in the payload, which they may or may not require in their logs. Additionally, if you only output the payload as-is into the .csv, it is really difficult to read the log entry as the entire payload string is written to a single column. It therefore needs to be split up further into smaller pieces via this sort of processing.

I plan to modify my extension to push these logs to a DB instead of a .csv file at some point, but either way, I'd still need to know how the payload is structured so I can extract the parts each customer is after and also be confident my code will handle all logging events correctly. I'm clearly missing something in my current implementation.

Is there any reason why the payload structure isn't currently public? Are you able to check if I can get a copy regardless?

Cheers!

**Comment by Afira-Zahari-i2** [comment]
Hi,

We have kept the structure internal to allow us to easily make changes as we see fit. I would note that the event payload does share similarities with the i2 Connect SPI [DaodRequestPayload](https://i2group.github.io/analyze-connect/content/rest/i2-connect-spi.html#cmp--schemas-daodrequestpayload) object, which you can use as a reference point. However, this must only be used as a guideline and it is not the source of truth for the event payload structure.

If there are specific fields that you want the `IDAODAuditEvent` to return and if you have support entitlement, you can raise a support [request](https://i2group.com/support-request) referencing this issue and it can be raised as a Request for Enhancement (RFE).

**Comment by nondeterminickstic** [comment]
Hi Afira,
Okay thanks for the info. I'll take a look at DaodRequestPayload object and see if I can work out what I'm missing.

Cheers.

**Comment by Anthony-Johnson-i2** [comment]
Hi @nondeterminickstic
I am  just checking back that we are good to close this and that you were able to progress with the information provided by Afira?

**Comment by nondeterminickstic** [comment]
Hi @Anthony-Johnson-i2, 
Thanks - all good to close.
